version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql-api
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: user_api_db
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
