version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-user-api
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_api_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
